// <auto-generated>
// This code was generated by a tool.
// </auto-generated>

using System;
using System.Threading.Tasks;
using Autofac;
using Autofac.Builder;
using Autofac.Grpc;
using Grpc.Net.Client;

namespace Grpc
{
    /// <summary>
    /// The RegistrationModule class.
    /// </summary>
    public class RegistrationModule
    {
        /// <summary>
        /// Sends registration information asynchronously.
        /// </summary>
        /// <returns>A task that represents the asynchronous operation.</returns>
        public static async Task SendRegistrationInfoAsync()
        {
            var registrationInfo = RegistrationInfoManager.Instance.RegistrationInfo;

            var data = new RegistrationRequest
            {
                Id = registrationInfo.Id,
                Name = registrationInfo.Name,
                Service = registrationInfo.Service,
                Dependencies = { registrationInfo.Dependencies },
                Implementations = { registrationInfo.Implementations }
            };

            var channel = GrpcChannel.ForAddress("http://localhost:5213/");
            var client = new Registrations.RegistrationsClient(channel);

            var send = await client.SendRegistrationInfoAsync(data);
            Console.WriteLine($"Response status: {send.Status}");
        }
    }
}
